### ISSUE TITLE
Editing vehicles max seats (or wheelchairs) can lead to wrong state

### ISSUE THREAD

**Issue by Em-Ant** [Em-Ant/fcc-options-app#10]
Example: If you have 5 consumers on Van 1, and you edit that van properties setting `maxSeats` to 3, you get an incorrect state. Before editing we should check for state coherence, and if an incorrect situation is requested, we should abort the update maybe asking to remove the surplus consumers first.

**Comment by paycoguy** [comment]
I will try to tackle this.  I think this can be done by trying to figure out how the mongoose-id-validator plugin works.

**Comment by paycoguy** [comment]
fixed via e30cb8e5fc9ee58dbc643e19ddefc06fc07f094c.

I added a pre validate schema middleware to invalidate the vehicle if consumers couldn't fit in the new vehicle configuration
