### ISSUE TITLE
When first loading app, the Bus 1 man icon incorrectly says 0 passengers

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#12]
It should have 1 passenger, since Gordon F. is on it.
http://screencast.com/t/UzkglmXF

**Comment by paycoguy** [comment]
I think this is related to #11.

**Comment by Em-Ant** [comment]
Gordon F. has wheelchair. Wheelchairs reporting was broken ( a typo in the related prop name). Man icon was correct, but wheelchair label was hidden.
