### ISSUE TITLE
Lazy loading can fail on server error.

### ISSUE THREAD

**Issue by Em-Ant** [Em-Ant/fcc-options-app#15]
If loading fails one time, data are not being requested anymore, on any page.

**Comment by paycoguy** [comment]
Fixed with 76450146ad53fccbf8ae8bdb2750d44ac7f293cd.  If any API fails because they are not authorized, the user is logged out on the client and sent back to the login screen.

**Comment by Em-Ant** [comment]
It's not only this. On every kind of error, `needsToBeFetched` is not reset, so no other page can reload data.

**Comment by Em-Ant** [comment]
ba61f9b should fix this, for the reducers part. Error handling in the components (i.e, try to reload, or display an error) not implemented yet
