### ISSUE TITLE
Add more seed data

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#17]
More vehicles with varying seating configurations as specified by Option's Inc.
More consumers located in other areas around Options, Inc (Elk River, Monticello,...)

**Comment by paycoguy** [comment]
I'll work on this now

**Comment by Em-Ant** [comment]
We can collaborate on the task. I think we should have at least 100 consumers.

**Comment by Em-Ant** [comment]
I think we are done with this. I close it.
