### ISSUE TITLE
Front-end authorization fails after closing the browser

### ISSUE THREAD

**Issue by Em-Ant** [Em-Ant/fcc-options-app#18]
![screenshot - 12042016 - 14 38 05](https://cloud.githubusercontent.com/assets/12955734/14460215/98135456-00bc-11e6-9aa1-1236e2c23134.png)

Login, then close the browser, the reopen it and point to te app. You will see the map page in perpetual loading state.

**Comment by paycoguy** [comment]
Fixed with 95910abb56da8a2bef0310e05426fec0a2262852.


@Em-Ant can you test it out?

**Comment by Em-Ant** [comment]
it's ok now. i'm closing this.
