### ISSUE TITLE
Adding consumer to deleted vehicle on map shows no errors

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#22]
Open 2 browsers
Browser 1: open vehicles page
Browser 2:  open map
Browser 1:  delete a vehicle
Browser 2:  add consumers to the deleted vehicle

The map shows no errors, and it looks like the consumer is added to the vehicle.

If you refresh the map, the vehicle is removed and the consumer has the unassigned state.

**Comment by Em-Ant** [comment]
fixed with b7b3acc
