### ISSUE TITLE
Adding identical consumer to 2 vehicles doesn't give an error

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#23]
I see that if you open 2 browsers and try to add the same consumer to 2 different vehicles, the consumer is added to the last vehicle, and removed from the 1st vehicle.

If the consumer is already on a vehicle, I think there should be an error when trying to add the consumer to another vehicle.  What do you think @Em-Ant?

**Comment by Em-Ant** [comment]
true. Now the server handler removes the user inserted from all other vehicles. How do we know if the consumer is on a vehicle, on server ?

**Comment by paycoguy** [comment]
Right now the server is removing the consumer from all vehicles before assigning.  I think this query can be changed to check if the consumer is on any vehicle. If so, then return an error, otherwise continue with the update.

**Comment by Em-Ant** [comment]
Fixed with  b7b3acc
