### ISSUE TITLE
Max passengers per vehicle constraint not being observed

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#24]
If the max passengers per vehicle is 14, you can add 15 passengers on a vehicle right now without an error.

**Comment by Em-Ant** [comment]
Can this be validated in the vehicles 'pre save' middleware ?

**Comment by Em-Ant** [comment]
This should fix this issue 028d2d6. Please, check it.
We still have to validate when lowering maximum Passengers on setting, with consumers on vehicles exceeding the new setting.

**Comment by paycoguy** [comment]
Looks good.  Closing this issue.  I'm going to open a new issue when updating new settings.
