### ISSUE TITLE
Max route time constraint not being observed

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#25]
If the max route time is 90 minutes, you can have a route of 100 minutes and there will be no errors.

**Comment by Em-Ant** [comment]
This could be handled displaying a warning when calculating directions, if that route exceeds the max time. I'm afraid that getting directions on every vehicle's consumers update would be really slow.

**Comment by paycoguy** [comment]
Yes, I agree that  putting a warning in the directions would be the best way to go.

**Comment by paycoguy** [comment]
Ok i'm working on this

**Comment by paycoguy** [comment]
Fixed with 3f6f38df57c1c9bf8b60d840fecef6cc90e83297
A warning is now displayed right below the Max Passenger Duration if this constraint fails.
