### ISSUE TITLE
Bug adding or editing a consumer with an empty name 

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#4]
When you press submit, the consumers box and form box are in a perpetual loading state.

**Comment by Em-Ant** [comment]
It works for me (Local and Remote). How did you get that error ?

**Comment by paycoguy** [comment]
http://screencast.com/t/kd7fNxYmY9W

**Comment by Em-Ant** [comment]
The 'spinning' state is not removed in the related error handler. I'll fix it now.
