### ISSUE TITLE
Consumers overlap consumer panel

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#43]
<img width="193" alt="screen shot 2016-05-02 at 9 29 29 am" src="https://cloud.githubusercontent.com/assets/15024773/14960259/b49c3c0a-1048-11e6-8b8f-0b8c9a712699.png">

**Comment by Em-Ant** [comment]
c1eef1c should fix it. It looks ok for me in chrome and firefox. Please check it in Safari.

**Comment by paycoguy** [comment]
Looks good on osx chrome and safari
