### ISSUE TITLE
Vehicles overlap vehicle panel

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#44]
<img width="298" alt="screen shot 2016-05-02 at 9 32 36 am" src="https://cloud.githubusercontent.com/assets/15024773/14960297/df579dfe-1048-11e6-8205-bb6b77db602f.png">

**Comment by Em-Ant** [comment]
c1eef1c should fix it. It looks ok for me in chrome and firefox. Please check it in Safari.

**Comment by paycoguy** [comment]
Looks good on chrome.

On safari, the active vehicle panel box doesn't push the rest of the vehicle panels down.  It overlaps them.

http://screencast.com/t/0eQILhLSx5

**Comment by paycoguy** [comment]
Closing this.  Keeping  #47 open.
