### ISSUE TITLE
Elements of Vehicle box overlap when adding a lot of consumers

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#45]
<img width="428" alt="screen shot 2016-05-02 at 9 33 55 am" src="https://cloud.githubusercontent.com/assets/15024773/14960367/2e552c96-1049-11e6-8563-7d22447d7f6d.png">

**Comment by Em-Ant** [comment]
c1eef1c should fix it. It looks ok for me in chrome and firefox. Please check it in Safari.

**Comment by paycoguy** [comment]
Looks good on osx chrome and firefox
