### ISSUE TITLE
Vehicle passengers don't show up in Safari

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#47]
Flex issue
<img width="227" alt="screen shot 2016-05-02 at 10 20 59 am" src="https://cloud.githubusercontent.com/assets/15024773/14961667/98e83552-104f-11e6-930d-0fcdd3766867.png">

**Comment by Em-Ant** [comment]
c1eef1c should fix it. It looks ok for me in chrome and firefox. Please check it in Safari.

**Comment by paycoguy** [comment]
On safari, the active vehicle panel box doesn't push the rest of the vehicle panels down. It overlaps them.
http://screencast.com/t/0eQILhLSx5

**Comment by paycoguy** [comment]
Works!
