### ISSUE TITLE
Clusters disappear after switching back to map from vehicle Route page

### ISSUE THREAD

**Issue by Em-Ant** [Em-Ant/fcc-options-app#61]
To reproduce the issue : 
1) Go to map page
2) Click on 'Configure Route' in the active vehicle box
3) Go back to map page, using the map icon in the  sidebar
Screenshot - 
![screenshot - 13052016 - 18 19 22](https://cloud.githubusercontent.com/assets/12955734/15254485/549e68da-1937-11e6-8bef-8d20d9f99b63.jpg)

**Comment by paycoguy** [comment]
fixed with ec1a0a4b4dd9223c9c8d7f18d2dfdfc1701933ba.  Manually cleared out clusterer when map page unmounts.
