### ISSUE TITLE
Consumer page in perpetual loading state after delete

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#69]
1.  Go to the map page
2.  Hover over a consumer marker to make the info window open
3.  Go to consumers page
4.  Delete that consumer that corresponds to the info window
5.  The consumers page will be in a perpetual loading state

**Comment by paycoguy** [comment]
fixed with ff3a2a9d6b89f3c9b03ae30081241236109be5a4

**Comment by Em-Ant** [comment]
Unfortunately it's not enough.
I tried to delete a consumer from the active vehicle, and I got `Type Error: consumerCluster is undefined`

**Comment by paycoguy** [comment]
Fixed with f10558b5731cbcc90e8037d9e39309452e16e1d9.

@Em-Ant Can you test this?

**Comment by Em-Ant** [comment]
All seem ok. I'm closing it.
