### ISSUE TITLE
Control sidebar doesn't open after initial login

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#7]

**Comment by paycoguy** [comment]
After an hour trying to debug this, I still cannot figure out why this bug still happens.  The rest of the adminLTE animation work properly after a login.  

I might have to move settings to the left side bar.

**Comment by paycoguy** [comment]
Another workaround is to separate the login page from react-router.

**Comment by Em-Ant** [comment]
I solved this using a custom toggle function with jquery, for the 'gears' button in the header.
There must be some initialization problem, but I wasn't able to find it. 93decf0
