### ISSUE TITLE
Changing wait time doesn't update max passenger duration 

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#81]
1.  Open a route and click on get directions
2.  Go to the settings sidebar
3.  Change the average route wait time
4.  The Max Passenger Duration and Total Duration do not update

Recalculating directions sets the Max Passenger Duration and Total Duration correctly

**Comment by Em-Ant** [comment]
closed via 0475f3aadf2722d1963f51b71c19df058663d050
