### ISSUE TITLE
Route doc report starting time wrong on heroku

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#82]

**Comment by Em-Ant** [comment]
Fixed with 794af82c0dd09d8fdedadcb7b1d085c236f293e5
and a31afe1e6ab54119cdd826fb4ab84b0a0e24bd6e

**Comment by Em-Ant** [comment]
I used unix timestamps for the default route start times, because the previous Date strings led to use of local server timezone. I added `moment.utc` to the report generator. 
de1be53ad10cde8c4b48294a188330c01fab7511
