### ISSUE TITLE
Add/Edit Form Behavior on Consumers/Vehicles/Users unclear

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#84]
I've had 3 people so far complain about the behavior of these forms.  People think there's a bug when you click when you add/edit a consumer/vehicle/user and they don't know that the form appears at the very bottom.

Some options:
1.  Immediately scroll to where the form is (probably the easiest)
2.  Make the form a modal dialog box (I think the expected behavior)
3.  Inline add/edit (would be really cool)

**Comment by Em-Ant** [comment]
check 747b4ad13668feffb9c6b6ea71872bcefc2cf789. is it OK for you ?

**Comment by paycoguy** [comment]
Looks great!  The scrolling makes it feel modern.
