### ISSUE TITLE
How to set up initial admin user(s) for client?

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#87]
We are not going to be using our regular seed.js file to seed the database.  

Should we create a separate seed file for client specific database entries?
Should we manually create client specific database entries in the client database ?

**Comment by paycoguy** [comment]
OK, I think I have the answer.  Right before we transfer the heroku app to options, we can set up the users collection to the client's liking.  We will most likely clear out the consumers/vehicles/directions collections right before the transfer.  How does this wound @Em-Ant ?

**Comment by Em-Ant** [comment]
I agree with you. I think we should clear the database dropping vehicles/consumers/directions (probably using the mLab console is the easiest way) and leave only one admin account set to a temporary login/password that Matt chooses. The current default account could work, if is OK for Matt. After the transfer Matt should create his own account(s), reset his password, and delete the temporary account

**Comment by paycoguy** [comment]
Sounds good.
