### ISSUE TITLE
Application delivery email

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#88]
@Em-Ant here is the email I plan to send Matt.  Are there things I missed in here?

Hi Matt,

Emanuelle and I are very excited to deliver this application to you.  We hope that this application will make your life easier in your organization.

Here is a list of items we will need from you to begin the delivery.

Google API Key

Google requires us to have a key to access their Google Maps Directions web service API.  Here's how to generate your API key.

Go to this link:
https://developers.google.com/maps/documentation/directions/

Scroll to the middle of the page and click on "GET A KEY"

Follow the instructions to create a project and generate are server API key.

Once you have the API key, you can email it to me and I'll configure the app to use your API key

Heroku account username

https://www.heroku.com/
You can go to this link and signup for a FREE account.  

Once we have your username, we will initiate the transfer using the steps in this link:
https://devcenter.heroku.com/articles/transferring-apps

Testing

After we do the transfer, we will test to see if everything is working properly.  If everything looks good, we will clean out all the test data in the database. 

Let me know if you have any questions about any of these steps.

Thanks,
Andre

**Comment by Em-Ant** [comment]
It looks ok.

The only thing i can add is that the heroku account needs to be verified 
i.e. they need to link a credit card in order to access the mLab plugin 
(even the free Sandbox version).


Il 28/05/2016 19:07, Andre Alonzo ha scritto:

**Comment by paycoguy** [comment]
Ok I sent and CC'd you the email.  I added that they need the account to be verified.
