### ISSUE TITLE
Video Presentation

### ISSUE THREAD

**Issue by paycoguy** [Em-Ant/fcc-options-app#90]
I'm aiming to make the video presentation 10 minutes or under.  I'm thinking of making a slideshow presentation for the non-demo portion of the video.  Here are the topics I'm thinking of covering.

1.  Introduction of Andre and Emanuele

2.  Options Inc
Where they are
What they do
Who they serve
Contact info

3.  Explanation of the problem
Options Inc provides transportation to approximately 230 individuals and manages a fleet of 23 vehicles.  

4.  Demo of the application

Login System 
Session based authentication

Overview of how to navigate the app
Map
Consumers
Vehicles
Users
Change Profile
Settings

Consumers Page
Show Adding a Consumer 
Show filtering
Show excel

Vehicles Page
Show Adding a  Vehicle 
Show excel

Map Page
Overview of map page
Vehicle Panel
Active Vehicle Panel
Map
Consumers Panel
Filters

Show adding/removing consumer to vehicle

Show configure route
Show optimize route
Show additional waypoints
Show get directions
Show start route time
Show print
Show docx

5.  Acknowledgements

Matt 
Michael
Jason
Quincy

Testers
George
Manuel
Orlando
Erkan

6.  Contact information
Andre
Emanuele

**Comment by Em-Ant** [comment]
The presentation looks great. I added some infos. I took a picture with a low-res cellphone camera. I had to make it B/W because colours were horrible. I hope it's good enough. It may sound crazy but I've not entered the smartphone era yet. I still proudly own and use an old nokia phone
